# Generated by Django 4.2.6 on 2024-01-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_readinggoal_date_created_readinggoal_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinggoal',
            options={'verbose_name': 'Reading Goal', 'verbose_name_plural': 'Reading Goals'},
        ),
        migrations.AlterModelOptions(
            name='readinggoalbook',
            options={'verbose_name': 'Reading Goal Book', 'verbose_name_plural': 'Reading Goal Books'},
        ),
    ]
