# Generated by Django 4.2.6 on 2025-03-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_readinggoal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggoal',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
