# Generated by Django 4.2.6 on 2023-10-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('CHAT', 'Chatter'), ('ATRIOC', 'Atrioc')], default='CHAT', max_length=6)),
                ('submitter', models.CharField(max_length=50)),
                ('stream_link', models.URLField()),
                ('amazon_link', models.URLField()),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title', 'author'],
                'unique_together': {('title', 'author')},
            },
        ),
    ]
