# Generated by Django 4.2.6 on 2023-10-20 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_amazon_link_alter_book_stream_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('CHAT', 'Chatter'), ('ATRIOC', 'Atrioc')], default='CHAT', help_text='Select Chatter or Atrioc Recommendation', max_length=6),
        ),
    ]
