# Generated by Django 4.2.6 on 2023-10-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_date_created_book_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['approved', 'title', 'author', 'date_created']},
        ),
    ]
