# Generated by Django 4.2.6 on 2023-11-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amazon_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='stream_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
