# Generated by Django 4.2.6 on 2024-01-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='currently_reading',
            field=models.BooleanField(default=False),
        ),
    ]
