# Generated by Django 4.2.6 on 2025-03-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_currently_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('CHAT', 'Chatter'), ('ATRIOC', 'Atrioc'), ('LEMONADESTAND', 'Lemonade Stand')], default='CHAT', help_text='Select Chatter, Atrioc, or Lemonade Stand Recommendation', max_length=13),
        ),
    ]
